# Generated by Django 4.2.7 on 2023-11-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_total_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
