# Generated by Django 4.2.7 on 2023-11-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_total_gen_app', '0002_alter_product_cost_price_alter_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kol_d',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
