# Generated by Django 4.2.7 on 2023-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_total_gen_app', '0006_alter_product_kol_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
