# Generated by Django 4.2.7 on 2023-11-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_total_gen_app', '0008_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
